version: '3.8'

services:
  postgres_local:
    image: postgres:16-alpine
    container_name: dopeDatabase
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: trabalho=lucifer
      POSTGRES_DB: dope_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: